# Config format schema number
format_version: 4

###################
## Model options
model_params:
  model_architecture: "cylinder_asym"

  output_shape:
    - 120
    - 360
    - 32

  fea_dim: 9
  out_fea_dim: 256
  num_class: 20
  num_input_features: 32 #16
  use_norm: True
  init_size: 32 #16
  num_scales: 2  # NUMA: Non-Uniform Multi-scale Aggregation (paper default=2)


###################
## Dataset options
dataset_params:
  dataset_type: "cylinder_dataset"
  pc_dataset_type: "SemKITTI_sk"
  ignore_label: 0
  return_test: False
  fixed_volume_space: True
  label_mapping: "./config/label_mapping/semantic-kitti.yaml"
  max_volume_space:
    - 50
    - 3.1415926
    - 2
  min_volume_space:
    - 1
    - -3.1415926
    - -4


###################
## Data_loader options
train_data_loader:
  data_path: "../../data/semantickitti/dataset/sequences/"
  imageset: "train"
  return_ref: True
  batch_size: 2 # effective batch_size=8 via accumulation_steps=4 in train_cyl_sem.py
  shuffle: True
  num_workers: 4 #4

val_data_loader:
  data_path: "../../data/semantickitti/dataset/sequences/"
  imageset: "val" #"val"
  return_ref: True
  batch_size: 1
  shuffle: False
  num_workers: 4 #4


###################
## Train params
train_params:
  model_load_path: "./model_load_dir/model_full_ft.pt"
  model_save_path: "./model_save_dir/model_full_ss.pt"
  checkpoint_path: "./model_save_dir/model_full_ss_checkpoint.pt"
  checkpoint_every_n_steps: 3189
  max_num_epochs: 40
  eval_every_n_steps: 3189
  learning_rate: 0.001
  instance_db_path: "./instance_db/semantickitti_instance_db.pkl"
